baseURL = "http://example.org/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Что есть истина?"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "ru"
# language name ["English", "Polski", ...]
languageName = "Russian"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false

# determines default content language ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "ru"

# default amount of posts in each pages
paginate = 12
# google analytics code [UA-XXXXXXXX-X]
# googleAnalytics = ""
# copyright description used only for seo schema
# copyright = "Wladimir Wendland"

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true

# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# Author config
[author]
  name = "Wladimir Wendland"
  email = "wladimir.wendland@gmail.com"
  link = "https://wtw24.com"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Заметки"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Категории"
    url = "/categories/"
    title = ""

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/wtw24/wtw24.com"
  # LoveIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = "sha256"
  # LoveIt NEW | 0.2.0 date format
  dateFormat = "02.01.2006"
  # website title for Open Graph and Twitter Cards
  title = "Что есть истина?"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "Добро пожаловать на мой сайт!"
  # website images for Open Graph and Twitter Cards
  # images = ["/logo.png"]

  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
  # LoveIt NEW | 0.2.0 Header title config
  [params.header.title]
    # URL of the LOGO
    logo = "/images/logo.png"
    # title name
    name = "Что есть истина?"
    # you can add extra information before the name (HTML format is supported), such as icons
#    pre = "<i class='fa fa-book-bible'></i> "
#    pre = "<i class='fa fa-cross'></i> "
#    pre = "<i class='fa fa-church'></i> "
    # you can add extra information after the name (HTML format is supported), such as icons
    # post = "_ <i class='fa fa-heart'></i> _ <i class='fa fa-cross'></i> _ <i class='fa fa-book-bible'></i>"
    # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
    typeit = false

  # Footer config
  [params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    # custom = ''
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = false
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2022
    # ICP info only in China (HTML format is supported)
    # icp = ""
    # license info (HTML format is supported)
    # license = ''

  # LoveIt NEW | 0.2.0 Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "02.01"
    # amount of RSS pages
    rss = 20

  # LoveIt NEW | 0.2.0 List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "02.01"
    # amount of RSS pages
    rss = 20

  # LoveIt NEW | 0.2.0 App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Что есть истина?"
    # whether to omit favicon resource links
    noFavicon = true
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"

  # LoveIt NEW | 0.2.0 Search config
  [params.search]
    enable = true
    # type of search engine ["lunr", "algolia"]
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # LoveIt NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # LoveIt NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
    highlightTag = "em"
    # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""

  # Home page config
  [params.home]
  # LoveIt NEW | 0.2.0 amount of RSS pages
  rss = 10
  # Home page profile
  [params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    # gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/avatar.png"
    # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
    title = "Добро пожаловать на мой сайт!"
    # subtitle shown in home page (HTML format is supported)
    subtitle = "Пока сайт находится в разработке. Принимаю все замечания и предложения по почте."
    # whether to use typeit animation for subtitle
    typeit = false
    # whether to show social links
    social = true
    # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
    disclaimer = "Спасибо, что зашли на мою страничку!"
  # Home page posts
  [params.home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6
    # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
    # default behavior when you don't set "hiddenFromHomePage" in front matter
    defaultHiddenFromHomePage = false

  # Social config about the author
  [params.social]
    GitHub = "wtw24"
#    Linkedin = ""
#    Twitter = "xxxx"
#    Instagram = "xxxx"
#    Facebook = "xxxx"
#    Telegram = "xxxx"
#    Medium = ""
#    Gitlab = ""
#    Youtubelegacy = ""
#    Youtubecustom = ""
#    Youtubechannel = ""
#    Tumblr = ""
#    Quora = ""
#    Keybase = ""
#    Pinterest = ""
#    Reddit = ""
#    Codepen = ""
#    FreeCodeCamp = ""
#    Bitbucket = ""
#    Stackoverflow = ""
#    Weibo = ""
#    Odnoklassniki = ""
#    VK = ""
#    Flickr = ""
#    Xing = ""
#    Snapchat = ""
#    Soundcloud = ""
#    Spotify = ""
#    Bandcamp = ""
#    Paypal = ""
#    Fivehundredpx = ""
#    Mix = ""
#    Goodreads = ""
#    Lastfm = ""
#    Foursquare = ""
#    Hackernews = ""
#    Kickstarter = ""
#    Patreon = ""
#    Steam = ""
#    Twitch = ""
#    Strava = ""
#    Skype = ""
#    Whatsapp = ""
#    Zhihu = ""
#    Douban = ""
#    Angellist = ""
#    Slidershare = ""
#    Jsfiddle = ""
#    Deviantart = ""
#    Behance = ""
#    Dribbble = ""
#    Wordpress = ""
#    Vine = ""
#    Googlescholar = ""
#    Researchgate = ""
#    Mastodon = ""
#    Thingiverse = ""
#    Devto = ""
#    Gitea = ""
#    XMPP = ""
#    Matrix = ""
#    Bilibili = ""
#    Discord = ""
#    DiscordInvite = ""
#    Lichess = ""
#    ORCID = ""
#    Pleroma = ""
#    Kaggle = ""
#    MediaWiki= ""
#    Plume = ""
#    HackTheBox = ""
#    RootMe= ""
#    Phone = ""
    Email = "wladimir.wendland@gmail.com"
    RSS = true # LoveIt NEW | 0.2.0

  # LoveIt CHANGED | 0.2.0 Page global config
  [params.page]
    # LoveIt NEW | 0.2.0 whether to hide a page from home page
    hiddenFromHomePage = false
    # LoveIt NEW | 0.2.0 whether to hide a page from search results
    hiddenFromSearch = false
    # LoveIt NEW | 0.2.0 whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = true
    # LoveIt NEW | 0.2.0 whether to enable the ruby extended syntax
    ruby = true
    # LoveIt NEW | 0.2.0 whether to enable the fraction extended syntax
    fraction = true
    # LoveIt NEW | 0.2.0 whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # LoveIt NEW | 0.2.4 whether to show the full text content in RSS
    rssFullText = false

  # LoveIt NEW | 0.2.0 Table of the contents config
  [params.page.toc]
    # whether to enable the table of the contents
    enable = true
    # LoveIt NEW | 0.2.9 whether to keep the static table of the contents in front of the post
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    auto = false

#  # LoveIt CHANGED | 0.2.0 KaTeX mathematical formulas
#  [params.page.math]
#    enable = true
#    # LoveIt CHANGED | 0.2.11 default inline delimiter is $ ... $ and \( ... \)
#    inlineLeftDelimiter = ""
#    inlineRightDelimiter = ""
#    # LoveIt CHANGED | 0.2.11 default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
#    blockLeftDelimiter = ""
#    blockRightDelimiter = ""
#    # KaTeX extension copy_tex
#    copyTex = true
#    # KaTeX extension mhchem
#    mhchem = true

  # LoveIt NEW | 0.2.0 Code config
  [params.page.code]
    # whether to show the copy button of the code block
    copy = true
    # the maximum number of lines of displayed code by default
    maxShownLines = 50

#  # LoveIt NEW | 0.2.0 Mapbox GL JS config
#  [params.page.mapbox]
#    # access token of Mapbox GL JS
#    accessToken = ""
#    # style for the light theme
#    lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
#    # style for the dark theme
#    darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
#    # whether to add NavigationControl
#    navigation = true
#    # whether to add GeolocateControl
#    geolocate = true
#    # whether to add ScaleControl
#    scale = true
#    # whether to add FullscreenControl
#    fullscreen = true

  # LoveIt CHANGED | 0.2.0 social share links in post page
  [params.page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = false
    Whatsapp = false
    Pinterest = false
    Tumblr = false
    HackerNews = false
    Reddit = false
    VK = true
    Buffer = false
    Xing = false
    Line = false
    Instapaper = false
    Pocket = false
    Flipboard = false
    Weibo = false
    Blogger = false
    Baidu = false
    Odnoklassniki = true
    Evernote = false
    Skype = false
    Trello = false
    Mix = false

  # LoveIt CHANGED | 0.2.0 Comment config
  [params.page.comment]
    enable = true

  # Disqus comment config
  [params.page.comment.disqus]
    # LoveIt NEW | 0.1.1
    enable = true
    # Disqus shortname to use Disqus in posts
    shortname = "wtw24blog"

#  # Gitalk comment config
#  [params.page.comment.gitalk]
#    # LoveIt NEW | 0.1.1
#    enable = false
#    owner = ""
#    repo = ""
#    clientId = ""
#    clientSecret = ""

#  # Valine comment config
#  [params.page.comment.valine]
#    enable = false
#    appId = ""
#    appKey = ""
#    placeholder = ""
#    avatar = "mp"
#    meta= ""
#    pageSize = 10
#    # automatically adapt the current theme i18n configuration when empty
#    lang = ""
#    visitor = true
#    recordIP = true
#    highlight = true
#    enableQQ = false
#    serverURLs = ""
#    # LoveIt NEW | 0.2.6 emoji data file name, default is "google.yml"
#    # ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
#    # located in "themes/LoveIt/assets/lib/valine/emoji/" directory
#    # you can store your own data files in the same path under your project:
#    # "assets/lib/valine/emoji/"
#    emoji = ""

#  # Facebook comment config
#  [params.page.comment.facebook]
#    enable = false
#    width = "100%"
#    numPosts = 10
#    appId = ""
#    # automatically adapt the current theme i18n configuration when empty
#    languageCode = ""

#  # LoveIt NEW | 0.2.0 Telegram comments config
#  [params.page.comment.telegram]
#    enable = false
#    siteID = ""
#    limit = 5
#    height = ""
#    color = ""
#    colorful = true
#    dislikes = false
#    outlined = false

#  # LoveIt NEW | 0.2.0 Commento comment config
#  [params.page.comment.commento]
#    enable = false

#  # LoveIt NEW | 0.2.5 utterances comment config
#  [params.page.comment.utterances]
#    enable = false
#    # owner/repo
#    repo = ""
#    issueTerm = "pathname"
#    label = ""
#    lightTheme = "github-light"
#    darkTheme = "github-dark"

#  # giscus comment config (https://giscus.app/)
#  [params.page.comment.giscus]
#    # You can refer to the official documentation of giscus to use the following configuration.
#    enable = false
#    repo = ""
#    repoId = ""
#    category = "Announcements"
#    categoryId = ""
#    # automatically adapt the current theme i18n configuration when empty
#    lang = ""
#    mapping = "pathname"
#    reactionsEnabled = "1"
#    emitMetadata = "0"
#    inputPosition = "bottom"
#    lazyLoading = false
#    lightTheme = "light"
#    darkTheme = "dark"

#  # LoveIt NEW | 0.2.7 Third-party library config
#  [params.page.library]
#  [params.page.library.css]
#  # someCSS = "some.css"
#  # located in "assets/"
#  # Or
#  # someCSS = "https://cdn.example.com/some.css"
#  [params.page.library.js]
#  # someJavascript = "some.js"
#  # located in "assets/"
#  # Or
#  # someJavascript = "https://cdn.example.com/some.js"
#  # LoveIt CHANGED | 0.2.10 Page SEO config
#  [params.page.seo]
#  # image URL
#  images = []
#  # Publisher info
#  [params.page.seo.publisher]
#  name = ""
#  logoUrl = ""

#  # LoveIt NEW | 0.2.5 TypeIt config
#  [params.typeit]
#    # typing speed between each step (measured in milliseconds)
#    speed = 100
#    # blinking speed of the cursor (measured in milliseconds)
#    cursorSpeed = 1000
#    # character used for the cursor (HTML format is supported)
#    cursorChar = "|"
#    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
#    duration = -1

#  # Site verification code config for Google/Bing/Yandex/Pinterest/Baidu
#  [params.verification]
#    google = ""
#    bing = ""
#    yandex = ""
#    pinterest = ""
#    baidu = ""

#  # LoveIt NEW | 0.2.10 Site SEO config
#  [params.seo]
#    # image URL
#    image = ""
#    # thumbnail URL
#    thumbnailUrl = ""
#
#  # LoveIt NEW | 0.2.0 Analytics config